version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  backend:
    build: ./MQTTBackend
    container_name: rabbitmq-backend
    ports: 
      - "5000:80"
    depends_on:
      - rabbitmq
  frontend: 
    build: ./rabbitmq-client
    container_name: rabbitmq-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  
